namespace CherryFramework.DataModels.Editor
{
    public static class CodeGenConstants
    {
        public const string FilenameEnd = ".Generated.cs";
        public const string BasePath = "Assets/Scripts";
        public const string ModelsPathAndNamespace = "GeneratedDataModels";

        public const string TemplateSuffix = "Template";
        public const string ModelSuffix = "Model";

        public static readonly string[] CopyAttributes = { "[JsonIgnore]", "[Newtonsoft.Json.JsonIgnoreAttribute()]" };

        public const string TemplateNamespaceSuffix = "DataModels.Templates";
        public const string TemplateNamespacePlaceholder = "##TEMPLATENAMESPACE##";
        public const string TemplateNamePlaceholder = "##TEMPLATE##";
        public const string ModelNamePlaceholder = "##MODEL##";
        public const string MemberNamePlaceholder = "##MEMBER##";
        public const string ConstructorPlaceholder = "##CTOR##";
        public const string PropsPlaceholder = "##PROPS##";
        public const string TypePlaceholder = "##TYPE##";
        public const string AttributesPlaceholder = "##ATTR##";

        public static readonly string ModelTemplate = $@"
// <auto-generated/>
// Do not modify by hand!
// To update this file, use ""Tools -> UnityCodeGen -> Generate"" main menu item

using System;
using Newtonsoft.Json;
using CherryFramework.DataModels;
using {TemplateNamespacePlaceholder};

namespace {ModelsPathAndNamespace}
{{
    [Serializable]
    public class {ModelNamePlaceholder} : DataModelBase
    {{
        private {TemplateNamePlaceholder} _template;
        
        public {ModelNamePlaceholder}() : base()
        {{
{ConstructorPlaceholder}
        }}
		
		public {ModelNamePlaceholder}({TemplateNamePlaceholder} source) : this()
        {{
	        if (source != null)
	        {{
		        if (source is ICloneable cloneable)
		        {{
			        _template = cloneable.Clone() as {TemplateNamePlaceholder};
		        }}
		        else
		        {{
			        throw new ArgumentException($""[{{this.GetType().Name}}] Tried to create new model with template source, but source is not ICloneable, which is not allowed!"");
		        }}
	        }}
	        else
	        {{
		        throw new ArgumentNullException(nameof(source));
	        }}
        }}
        
        // ReSharper disable InconsistentNaming
{PropsPlaceholder}
        // ReSharper restore InconsistentNaming
    }}
}}
";
        public static readonly string PropertyTemplate = $@"
        {AttributesPlaceholder}public {TypePlaceholder} {MemberNamePlaceholder}
        {{
            get => _template.{MemberNamePlaceholder};
            set {{ _template.{MemberNamePlaceholder} = value;
            Send<{TypePlaceholder}>(nameof({MemberNamePlaceholder}), value); }}
        }}     
        [JsonIgnore]  
        public Accessor<{TypePlaceholder}> {MemberNamePlaceholder}Accessor;
";
    }
}